//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Text
    {
        public int id { get; set; }
        public string text1 { get; set; }
        public int idP { get; set; }
    
        public virtual Object Object { get; set; }
    }
}
